---
language: python
services: docker

env:
  global:
    - ROLE_NAME: mysql
    - TRAVIS_SECURE_ENV_VARS: true
  matrix:
    - MOLECULE_DISTRO: ubuntu1604
    - MOLECULE_DOCKER_COMMAND: "/bin/systemd"

install:
  - pip install molecule docker

script: molecule test

# before_deploy:
#   - git config --local user.name $GITHUB_USER
#   - git config --local user.email $GITHUB_EMAIL
after_success:
  deploy:
    provider: releases
    skip_cleanup: true
    api_key:
      secure: $GITHUB_API_TOKEN
    file: ansible_role_$ROLE_NAME
    on:
      repo: ecaepp/ansible_role_$ROLE_NAME
      branch: master
      tags: true
    
  notifications:
    webhooks: https://galaxy.ansible.com/api/v1/notifications/
