---
- name: MySQL - Update mysql root passwd
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ mysql_root_password }}"
    login_user: "{{ mysql_root_username }}"
    login_password: "{{ mysql_root_default_password }}"
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: copy root my.cnf file
  template:
    src: templates/root.cnf.j2
    dest: /root/.my.cnf
  notify: "restart mysql"
