---
- name: Create MySQL user accounts and assign privs
  mysql_user:
    host: "{{ item.host }}"
    user: "{{ item.name }}"
    password: "{{ item.password }}"
    priv: "{{ item.priv }}"
    state: "{{ item.state }}"
    append_privs: "{{ item.append_privs }}"
    encrypted: "{{ item.encrypted }}"
  with_items: "{{ mysql_users }}"
  no_log: true
