---
- name: Installing MySQL-{{ mysql_version }}
  apt:
    pkg: mysql-server
    state: present
    update_cache: true

- name: Installing dependences {{ dependences }}
  apt:
    pkg: "{{ dependences }}"
    state: present

- name: Enable and started MySQL
  service:
    name: mysql
    state: started
    enabled: true
