---
- name: MySQL - Running pre_tasks
  include_tasks: pre_tasks.yml

- name: MySQL - Installing MySQL server for {{ ansible_distribution }}-{{ ansible_distribution_version }}
  include_tasks: Debian_install.yml
  when:
    - ansible_os_family == 'Debian'
    - mysql_bin.stat.exists == False

- name: MySQL - Secure Setup
  include_tasks: secure_setup.yml

- name: MySQL - Generate config files from templates
  include_tasks: configuration.yml

- name: MySQL - Creating database(s)
  include_tasks: create_database.yml
  when:
    - 'mysql_database is defined'
    - 'mysql_database != None'

- name: MySQL - Create database accounts
  include_tasks: database_users.yml
  when:
    - 'mysql_users is defined'
    - 'mysql_users != None'
