---
- name: Installing MySQL server for {{ ansible_distribution }}-{{ ansible_distribution_version }}
  include_tasks: Debian_install.yml
  when: ansible_os_family == 'Debian'

- name: Enable and start MySQL
  service:
    name: mysql
    enabled: true
    state: started

- name: MySQL - Update mysql root passwd
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ mysql_root_new_pass }}"
    login_user: "{{ mysql_root_user }}"
    login_password: "{{ mysql_root_old_pass }}"
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: MySQL - Delete anonymous mysql user
  mysql_user:
    name: ""
    state: absent
    login_user: root
    login_password: "{{ mysql_root_new_pass }}"

- name: MySQL - Remove mysql test database
  mysql_db:
    name: test
    state: absent
    login_user: root
    login_password: "{{ mysql_root_new_pass }}"

- name: Generate /etc/my.cnf config
  template:
    src: templates/server.cnf.j2
    dest: /etc/mysql/conf.d/my.cnf
    owner: root
    group: root
    mode: 0644
