---
- name: Installing MySQL-{{ mysql_version }}
  apt:
    pkg: mysql-server-{{ mysql_version }}
    state: present
    update_cache: true

- name: Installing dependences {{ dependences }}
  apt:
    pkg: "{{ dependences }}"
    state: present

- name: Enable and start MySQL
  service:
    name: mysql
    enabled: true
    state: started

- name: MySQL - Update mysql root passwd
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ mysql_root_new_pass }}"
    login_user: "{{ mysql_root_user }}"
    login_password: "{{ mysql_root_old_pass }}"
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
    # when: mysql_root_new_pass != mysql_root_old_pass and
    #       mysql_root_new_pass != ""

- name: MySQL - Delete anonymous mysql user
  mysql_user:
    name: ""
    state: absent
    login_user: root
    login_password: "{{ mysql_root_new_pass }}"

- name: MySQL - Remove mysql test database
  mysql_db:
    name: test
    state: absent
    login_user: root
    login_password: "{{ mysql_root_new_pass }}"

- name: Restart MySQL
  service:
    name: mysql
    state: restarted
