---
- name: Running pre_tasks
  include_tasks: pre_tasks.yml

- name: Installing MySQL server for {{ ansible_distribution }}-{{ ansible_distribution_version }}
  include_tasks: Debian_install.yml
  when: 
  - ansible_os_family == 'Debian'
  - mysql_bin.stat.exists == False

- include_tasks: configure_users.yml

- name: MySQL - Delete anonymous mysql user
  mysql_user:
    name: ""
    state: absent
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: MySQL - Remove mysql test database
  mysql_db:
    name: test
    state: absent
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: Generate /etc/my.cnf config
  template:
    src: templates/server.cnf.j2
    dest: /etc/mysql/conf.d/my.cnf
    owner: root
    group: root
    mode: 0644
